# Generated by Django 3.0.7 on 2020-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('publications_date', models.DateField(verbose_name='Fecha de Publicacion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Libros',
                'ordering': ['id_book'],
            },
        ),
    ]
