# Generated by Django 3.0.7 on 2020-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_comment',
            field=models.ManyToManyField(to='comment.Comment'),
        ),
    ]
