# Generated by Django 3.0.7 on 2020-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_id_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id_book'], 'verbose_name': 'Book', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_comment',
        ),
    ]
