# Generated by Django 3.0.7 on 2020-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_user'),
        ('book', '0003_auto_20200710_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_comment',
            field=models.ManyToManyField(to='comment.Comment'),
        ),
    ]
